CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'muguveli'@'%' IDENTIFIED BY '313132sa';
GRANT ALL PRIVILEGES ON wordpress.* TO 'muguveli'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';